/**
 * EDTECH ARCHITECTURE: MODULE M1 (LEVEL A1 - BREAKTHROUGH)
 * CORRECTED VERSION - 21 Lessons
 * Additions: Present Continuous (lesson 03)
 */

const m1Data = [
    { id: 1, title: "01. Verb To Be: Identity & States", explanation: "O **Verb To Be** (am, is, are) é a fundação. Ele não exige auxiliares para perguntas ou negativas. <br><b>Usage:</b> Names, Nationalities, Professions, and Feelings.", exercises: [{ question: "They ___ (be) from Japan.", answer: "are", tip: "Use 'are' for plural (They/We/You)." }, { question: "I ___ (be) a student.", answer: "am", tip: "First person uses 'am'." }], llmPrompt: "Act as a border control officer. Ask for my name, nationality, and job using only the Verb To Be." },
    { id: 2, title: "02. Present Simple: Habits & Routines", explanation: "Ações repetitivas. Regra crucial: **3rd Person -s** (He/She/It). <br><b>Auxiliaries:</b> DO/DOES.", exercises: [{ question: "Sarah ___ (work) at 9 AM.", answer: "works", tip: "Add -s for She." }, { question: "___ you drink coffee?", answer: "Do", tip: "Auxiliary for 'You'." }], llmPrompt: "Roleplay: Interview me about my morning routine using Do/Does. Summarize it using the 3rd person -s." },
    { id: 3, title: "03. Present Continuous: Actions Happening Now", explanation: "Para descrever o que está acontecendo <b>agora</b> ou em torno do momento presente. <br><b>Structure:</b> Am/Is/Are + Verb-ING. <br><b>Spelling:</b> run → runn<b>ing</b>, make → mak<b>ing</b>.", exercises: [{ question: "She ___ (read) a book right now.", answer: "is reading", tip: "She → Is + Verb-ING." }, { question: "We ___ (not/watch) TV at the moment.", answer: "are not watching", tip: "We → Are + not + Verb-ING." }], llmPrompt: "Roleplay: Nosy Neighbor. Ask me 5 questions about what I am doing right now, what my family members are doing, and what noise you can hear. Use 'Is he/she...ing?' and 'Are you...ing?'." },
    { id: 4, title: "04. Articles A/An & The", explanation: "**A/An** para algo não específico (A dog). **The** para algo específico ou único (The sun).", exercises: [{ question: "I have ___ (a/an) apple.", answer: "an", tip: "Use 'an' before vowel sounds." }, { question: "___ sky is blue today.", answer: "The", tip: "Specific/Unique objects use 'The'." }], llmPrompt: "Context: I am showing you my room. Ask me about 5 objects using 'Is that a...' or 'Where is the...'." },
    { id: 5, title: "05. Plurals: Regular & Irregular", explanation: "A maioria recebe -s. Exceções críticas: **Men, Women, Children, People, Teeth, Feet.**", exercises: [{ question: "There are two ___ (man) here.", answer: "men", tip: "Irregular plural of man." }, { question: "I have three ___ (child).", answer: "children", tip: "Irregular plural of child." }], llmPrompt: "Task: Describe a busy park scene using at least 3 irregular plural nouns." },
    { id: 6, title: "06. Possessive Adjectives (My, Your, His...)", explanation: "Sempre acompanham um substantivo para indicar posse. <br><b>Ex:</b> My car, Her house, Their cat.", exercises: [{ question: "This is ___ (I) phone.", answer: "my", tip: "Possessive for 'I'." }, { question: "___ (She) name is Mary.", answer: "Her", tip: "Possessive for 'She'." }], llmPrompt: "Context: Introduce your family members and their professions using possessive adjectives." },
    { id: 7, title: "07. Genitive Case ('s)", explanation: "Indica posse direta entre pessoas ou animais. <br><b>Ex:</b> John's dog (O cachorro do John).", exercises: [{ question: "That is ___ (Peter) laptop.", answer: "Peter's", tip: "Add 's to the owner." }, { question: "My ___ (parents) car is old.", answer: "parents'", tip: "If plural ends in 's', just add the apostrophe." }], llmPrompt: "Context: Family Reunion. Ask me 'Whose item is this?' for 5 different people using the 's." },
    { id: 8, title: "08. There is / There are & City Places", explanation: "**There is** (singular), **There are** (plural). <br><b>Vocab:</b> Hospital, Bakery, Mall.", exercises: [{ question: "___ (Existir) a park nearby.", answer: "There is", tip: "Singular existence." }, { question: "___ (Existir) two banks here.", answer: "There are", tip: "Plural existence." }], llmPrompt: "Roleplay: You are a tour guide. Describe a fictional town using 'There is/are'." },
    { id: 9, title: "09. Prepositions of Time (In, On, At)", explanation: "<b>IN:</b> Months/Years. <b>ON:</b> Days/Dates. <b>AT:</b> Specific Times/Points.", exercises: [{ question: "I study ___ night.", answer: "at", tip: "Exception: At night." }, { question: "The class is ___ Monday.", answer: "on", tip: "Days of the week use 'on'." }], llmPrompt: "Task: Create a schedule for our weekend trip using 'in', 'on', and 'at'." },
    { id: 10, title: "10. Prepositions of Place", explanation: "Descrevem localização física. <br><b>Vocab:</b> In, On, Under, Next to, Between, Behind.", exercises: [{ question: "The keys are ___ the table.", answer: "on", tip: "Position: Surface." }, { question: "Sit ___ (entre) Mary and Paul.", answer: "between", tip: "Position: In the middle of two." }], llmPrompt: "Context: Help me find my lost cat. Tell me to look in, under, and behind furniture." },
    { id: 11, title: "11. Numbers & Natural Time", explanation: "Números 1-100 e leitura de relógio. <br><b>Ex:</b> Half past (30 min), Quarter to (15 min para).", exercises: [{ question: "10:30 is 'Half ___ ten'.", answer: "past", tip: "30 minutes after." }, { question: "15:45 is 'Quarter ___ four'.", answer: "to", tip: "15 minutes until next hour." }], llmPrompt: "Act as a train announcer. Give me a schedule of 5 departures using natural time." },
    { id: 12, title: "12. Modals: Ability (Can / Can't)", explanation: "Capacidade técnica. Invariável (não muda para He/She/It).", exercises: [{ question: "He ___ (can) speak French.", answer: "can", tip: "No -s for modals." }, { question: "I ___ (cannot) swim.", answer: "can't", tip: "Negative contraction." }], llmPrompt: "Roleplay: Superhero Audition. Ask me what I 'can' and 'can't' do." },
    { id: 13, title: "13. Quantifiers: Some & Any", explanation: "**Some** para afirmativas. **Any** para negativas e perguntas.", exercises: [{ question: "I have ___ water.", answer: "some", tip: "Affirmative sentence." }, { question: "Do you have ___ milk?", answer: "any", tip: "Question form." }], llmPrompt: "Context: Cooking. Ask me 'Do we have any...?' for 5 ingredients." },
    { id: 14, title: "14. Demonstratives (This, That, These, Those)", explanation: "Perto (This/These). Longe (That/Those).", exercises: [{ question: "___ (Este aqui) book is good.", answer: "this", tip: "Singular and near." }, { question: "___ (Aqueles lá) are my friends.", answer: "those", tip: "Plural and far." }], llmPrompt: "Task: We are at a museum. Point at 5 objects near and far from us." },
    { id: 15, title: "15. Adjectives: Opposites", explanation: "Mapeamento léxico básico. <br><b>Ex:</b> Big/Small, Tall/Short, Rich/Poor, Happy/Sad.", exercises: [{ question: "The opposite of 'Expensive' is ___.", answer: "cheap", tip: "Vocabulary check." }, { question: "The opposite of 'Late' is ___.", answer: "early", tip: "Vocabulary check." }], llmPrompt: "Task: Compare two famous people using at least 4 pairs of opposites." },
    { id: 16, title: "16. Possessive Pronouns (Mine, Yours, Ours)", explanation: "Substituem o substantivo. <br><b>Ex:</b> 'It is mine' (É meu) em vez de 'It is my car'.", exercises: [{ question: "That bag is ___ (I).", answer: "mine", tip: "Pronoun for 'I'." }, { question: "This is yours and that is ___ (she).", answer: "hers", tip: "Pronoun for 'She'." }], llmPrompt: "Context: Lost and Found. Claim your items using possessive pronouns." },
    { id: 17, title: "17. Imperatives: Directions & Rules", explanation: "Verbo direto (sem 'to'). <br><b>Ex:</b> 'Turn left', 'Don't stop'.", exercises: [{ question: "___ (Vá) to the corner.", answer: "Go", tip: "Base form for commands." }, { question: "___ (Não) park here.", answer: "Don't", tip: "Negative command." }], llmPrompt: "Roleplay: You are a GPS. Give me 5 directions to reach the hospital." },
    { id: 18, title: "18. Question Words: Whose & Which", explanation: "**Whose** (Posse). **Which** (Escolha entre opções).", exercises: [{ question: "___ car is this? Peter's?", answer: "Whose", tip: "Asking about possession." }, { question: "___ color do you want: Red or Green?", answer: "Which", tip: "Choice between options." }], llmPrompt: "Task: Personal Shopper. Ask me choices using 'Which' and ask about my current items using 'Whose'." },
    { id: 19, title: "19. Basic Connectors (And, But, Or, Because)", explanation: "A coesão textual começa aqui. Usamos conectores para unir ideias. <br><b>And:</b> Adição. <br><b>But:</b> Contraste. <br><b>Or:</b> Alternativa. <br><b>Because:</b> Razão/Motivo.", exercises: [{ question: "I like coffee ___ I don't like tea.", answer: "but", tip: "Use for contrast." }, { question: "I am happy ___ it is my birthday.", answer: "because", tip: "Use to give a reason." }], llmPrompt: "Task: Describe your best friend. Use 'and' for qualities, 'but' for one defect, and 'because' to explain why you like them." },
    { id: 20, title: "20. Object Pronouns (Me, You, Him, Her...)", explanation: "Essencial para não repetir nomes. O pronome de objeto recebe a ação. <br><b>Ex:</b> 'I love Mary' -> 'I love **her**'.", exercises: [{ question: "Can you help ___ (eu)?", answer: "me", tip: "Object pronoun for 'I'." }, { question: "I see the boys. I see ___.", answer: "them", tip: "Object pronoun for 'They'." }], llmPrompt: "Context: A secret crush. Tell a friend about someone you like without saying their name, using only object pronouns (him/her/them)." },
    { id: 21, title: "21. Social English: Greetings & Fixed Chunks", explanation: "O 'Lexical Approach' puro. Expressões prontas que não traduzimos literalmente. <br><b>Ex:</b> 'Nice to meet you', 'How's it going?', 'See you later', 'You're welcome'.", exercises: [{ question: "Response to 'Thank you' is 'You are ___'.", answer: "welcome", tip: "Fixed social response." }, { question: "___ to meet you.", answer: "Nice", tip: "Greeting used when meeting someone new." }], llmPrompt: "Roleplay: You are at a networking event. Introduce yourself, ask how the other person is, and say goodbye using at least 5 fixed social chunks." }
];
